 -- =========================================================
-- PROYECTO FINAL
-- SISTEMA DE GESTIÓN DE CONCESIONARIO DE MOTOS
-- =========================================================



-- =========================================================
-- CLIENTES
-- =========================================================
CREATE TABLE mt_clientes (
    cliente_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tipo_doc VARCHAR2(5) NOT NULL,
    num_doc VARCHAR2(20) NOT NULL,
    nombre VARCHAR2(30) NOT NULL,
    telefono VARCHAR2(15),
    email VARCHAR2(50),
    estado VARCHAR2(15) DEFAULT 'ACTIVO' NOT NULL,
    
--Constraints
  CONSTRAINT pk_mt_clientes PRIMARY KEY(cliente_id),
  CONSTRAINT uq_mt_cliente_doc UNIQUE (tipo_doc, num_doc),
  CONSTRAINT ck_mt_cliente_estado CHECK (estado IN ('ACTIVO','INACTIVO')),
  CONSTRAINT ck_mt_cli_tipo_doc CHECK (tipo_doc IN ('CC', 'CE', 'NIT', 'PP'))
  )
  
  
-- =========================================================
-- MOTOS
-- =========================================================
CREATE TABLE mt_motos (
    moto_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    placa VARCHAR2(10) NOT NULL,
    marca VARCHAR2(30) NOT NULL,
    modelo VARCHAR2(40) NOT NULL,
    año_fabricacion NUMBER(5) NOT NULL,
    cilindraje NUMBER(5) NOT NULL,
    color VARCHAR2(20),
    precio NUMBER(12, 2) NOT NULL,
    estado VARCHAR2(15) DEFAULT 'DISPONIBLE' NOT NULL,
    
  -- Constraints
  CONSTRAINT pk_mt_motos PRIMARY KEY (moto_id),
  CONSTRAINT uq_mt_moto_placa UNIQUE (placa),
  CONSTRAINT ck_mt_estado CHECK (estado IN('DISPONIBLE', 'VENDIDA')),
  CONSTRAINT ck_mt_moto_cilindraje CHECK (cilindraje > 0),
  CONSTRAINT ck_mt_moto_año CHECK (año_fabricacion >= 2000),
  CONSTRAINT ck_mt_moto_precio CHECK (precio >= 0)
  )
  
  
-- =========================================================
-- COMPRAS
-- =========================================================
CREATE TABLE mt_compras (
    compra_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    cliente_id NUMBER NOT NULL,
    moto_id NUMBER NOT NULL,
    fecha_compra DATE NOT NULL,
    monto_total NUMBER(12, 2) NOT NULL,
    tipo_venta VARCHAR2 (15) DEFAULT 'CONTADO' NOT NULL,
    estado VARCHAR2 (15) DEFAULT 'ACTIVA' NOT NULL,
    
  -- Constraints
  CONSTRAINT pk_mt_compras PRIMARY KEY (compra_id),
  CONSTRAINT fk_mt_comp_cliente FOREIGN KEY (cliente_id) REFERENCES mt_clientes(cliente_id),
  CONSTRAINT fk_mt_comp_moto FOREIGN KEY (moto_id) REFERENCES mt_motos(moto_id),
  CONSTRAINT uq_mt_compra_moto UNIQUE (moto_id),
  CONSTRAINT ck_mt_comp_monto CHECK (monto_total >= 0),
  CONSTRAINT ck_mt_comp_tipo CHECK (tipo_venta IN ('CONTADO', 'FINANCIADO')),
  CONSTRAINT ck_mt_comp_estado CHECK (estado IN('ACTIVA', 'CANCELADA', 'PAGO'))
  )
  
  
-- =========================================================
-- PAGOS
-- =========================================================
CREATE TABLE mt_pagos (
    pago_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    compra_id NUMBER NOT NULL,
    fecha_pago DATE NOT NULL,
    monto_pago NUMBER(12, 2) NOT NULL,
    canal_pago VARCHAR2(20) NOT NULL,
    referencia VARCHAR2(30),
    
    
  -- Constraints
  CONSTRAINT pk_mt_pago PRIMARY KEY (pago_id),
  CONSTRAINT fk_mt_pago_comp FOREIGN KEY (compra_id) REFERENCES mt_compras(compra_id),
  CONSTRAINT ck_mt_monto_pago CHECK (monto_pago >= 0),
  CONSTRAINT ck_mt_pago_canal CHECK (canal_pago IN ('EFECTIVO', 'TRANSFERENCIA', 'TC', 'PSE')),
  CONSTRAINT uq_mt_pago_ref UNIQUE (referencia)
  )

---------------
DROP TABLE mt_pagos
DROP TABLE mt_compras
DROP TABLE mt_motos
DROP TABLE mt_clientes

----------------
SELECT * FROM mt_clientes
SELECT * FROM mt_motos
SELECT * FROM mt_pagos
SELECT * FROM mt_compras

COMMIT

